using KaloriUygulama.Data;
using KaloriUygulama.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace KaloriUygulama.InitialStrategies
{
    public class DbInitialStrategy : CreateDatabaseIfNotExists<KaloriUygulamaDbContext>
    {
        protected override void Seed(KaloriUygulamaDbContext context)
        {
            if (!context.Kullanicilar.Any())
            {
                context.Kullanicilar.Add(new Kullanici
                {
                    Id = 1,
                    Ad = "admin",
                    Soyad = "admin",
                    Eposta = "admin",
                    Parola = "admin",
                    SifreIpucu = "admin"
                });
            }

            List<Kategori> kategoriListesi = null;
            if (!context.Kategoriler.Any())
            {
                kategoriListesi = new List<Kategori>();
                kategoriListesi.Add(new Kategori { Id = 1, KategoriAd = "Mezeler" });
                kategoriListesi.Add(new Kategori { Id = 2, KategoriAd = "Çorbalar" });
                kategoriListesi.Add(new Kategori { Id = 3, KategoriAd = "Ana Yemekler" });
                kategoriListesi.Add(new Kategori { Id = 4, KategoriAd = "Yan Öğünler" });
                kategoriListesi.Add(new Kategori { Id = 5, KategoriAd = "Ekmekler ve Unlu Mamuller" });
                kategoriListesi.Add(new Kategori { Id = 6, KategoriAd = "Salatalar ve Salata Sosları" });
                kategoriListesi.Add(new Kategori { Id = 7, KategoriAd = "Soslar ve Çeşniler" });
                kategoriListesi.Add(new Kategori { Id = 8, KategoriAd = "Tatlılar" });
                kategoriListesi.Add(new Kategori { Id = 9, KategoriAd = "Aperatifler" });
                kategoriListesi.Add(new Kategori { Id = 10, KategoriAd = "İçecekler" });
                kategoriListesi.Add(new Kategori { Id = 11, KategoriAd = "Kahvaltı" });
                kategoriListesi.Add(new Kategori { Id = 12, KategoriAd = "Öğle Yemeği" });
                kategoriListesi.Add(new Kategori { Id = 13, KategoriAd = "Diğer" });
                foreach (Kategori item in kategoriListesi)
                {
                    context.Kategoriler.Add(item);
                }
            }

            List<Porsiyon> porsiyonListesi = null;
            if (!context.Porsiyonlar.Any())
            {
                porsiyonListesi = new List<Porsiyon>();
                porsiyonListesi.Add(new Porsiyon { Id = 1, PorsiyonAd = "Gram" });
                porsiyonListesi.Add(new Porsiyon { Id = 2, PorsiyonAd = "Adet" });
                porsiyonListesi.Add(new Porsiyon { Id = 3, PorsiyonAd = "Adet (Küçük)" });
                porsiyonListesi.Add(new Porsiyon { Id = 4, PorsiyonAd = "Adet (Orta)" });
                porsiyonListesi.Add(new Porsiyon { Id = 5, PorsiyonAd = "Adet (Büyük)" });
                porsiyonListesi.Add(new Porsiyon { Id = 6, PorsiyonAd = "Su Bardağı (200ml)" });
                porsiyonListesi.Add(new Porsiyon { Id = 7, PorsiyonAd = "Kupa (Küçük)" });
                porsiyonListesi.Add(new Porsiyon { Id = 8, PorsiyonAd = "Kupa (Orta)" });
                porsiyonListesi.Add(new Porsiyon { Id = 9, PorsiyonAd = "Kupa (Büyük)" });
                porsiyonListesi.Add(new Porsiyon { Id = 10, PorsiyonAd = "Kutu" });
                porsiyonListesi.Add(new Porsiyon { Id = 11, PorsiyonAd = "Parça (Küçük)" });
                porsiyonListesi.Add(new Porsiyon { Id = 12, PorsiyonAd = "Parça (Orta)" });
                porsiyonListesi.Add(new Porsiyon { Id = 13, PorsiyonAd = "Parça (Büyük)" });
                porsiyonListesi.Add(new Porsiyon { Id = 14, PorsiyonAd = "Paket" });
                porsiyonListesi.Add(new Porsiyon { Id = 15, PorsiyonAd = "Top" });
                porsiyonListesi.Add(new Porsiyon { Id = 16, PorsiyonAd = "Dilim" });
                porsiyonListesi.Add(new Porsiyon { Id = 17, PorsiyonAd = "Dilim (İnce)" });
                porsiyonListesi.Add(new Porsiyon { Id = 18, PorsiyonAd = "Dilim (Orta)" });
                porsiyonListesi.Add(new Porsiyon { Id = 19, PorsiyonAd = "Dilim (Kalın)" });
                porsiyonListesi.Add(new Porsiyon { Id = 20, PorsiyonAd = "Porsiyon (Küçük)" });
                porsiyonListesi.Add(new Porsiyon { Id = 21, PorsiyonAd = "Porsiyon (Orta)" });
                porsiyonListesi.Add(new Porsiyon { Id = 22, PorsiyonAd = "Porsiyon (Büyük)" });
                porsiyonListesi.Add(new Porsiyon { Id = 23, PorsiyonAd = "Çorba Kaşığı" });
                porsiyonListesi.Add(new Porsiyon { Id = 24, PorsiyonAd = "Çorba Kaşığı (Tepeleme)" });
                porsiyonListesi.Add(new Porsiyon { Id = 25, PorsiyonAd = "Tatlı Kaşığı" });
                porsiyonListesi.Add(new Porsiyon { Id = 26, PorsiyonAd = "Kase" });
                porsiyonListesi.Add(new Porsiyon { Id = 27, PorsiyonAd = "Tabak" });
                foreach (Porsiyon item in porsiyonListesi)
                {
                    context.Porsiyonlar.Add(item);
                }
            }


            if (!context.Besinler.Any())
            {
                List<Besin> besinListesi = new List<Besin>();
                besinListesi.Add(new Besin { BesinAd = "Fava", Gram = 130m, Kalori = 147m, Karbonhidrat = 8.8m, Protein = 7.2m, Yag = 9m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 1), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "fava.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Fava", Gram = 20m, Kalori = 23m, Karbonhidrat = 1.4m, Protein = 1.1m, Yag = 1.4m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 1), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 23), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "fava.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Fava", Gram = 1m, Kalori = 1m, Karbonhidrat = 0.1m, Protein = 0.1m, Yag = 0.1m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 1), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "fava.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Mercimek Köftesi", Gram = 225m, Kalori = 291m, Karbonhidrat = 38.1m, Protein = 9.1m, Yag = 10.2m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 1), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "mercimekKöftesi.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Mercimek Köftesi", Gram = 30m, Kalori = 39m, Karbonhidrat = 5.1m, Protein = 1.2m, Yag = 1.4m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 1), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 4), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "mercimekKöftesi.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Mercimek Köftesi", Gram = 1m, Kalori = 1m, Karbonhidrat = 0.2m, Protein = 0, Yag = 0, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 1), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "mercimekKöftesi.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Paçanga Böreği", Gram = 136m, Kalori = 504m, Karbonhidrat = 17.9m, Protein = 14.8m, Yag = 42.6m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 1), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "Pacanga.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Paçanga Böreği", Gram = 1m, Kalori = 4m, Karbonhidrat = 0.1m, Protein = 0.1m, Yag = 0.3m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 1), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "Pacanga.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Tarhana Çorbası", Gram = 200m, Kalori = 121m, Karbonhidrat = 10m, Protein = 4.6m, Yag = 6.6m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 2), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 26), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tarhana.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Tarhana Çorbası", Gram = 10m, Kalori = 6m, Karbonhidrat = 0.5m, Protein = 0.2m, Yag = 0.3m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 2), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 23), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tarhana.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Tarhana Çorbası", Gram = 250m, Kalori = 151m, Karbonhidrat = 12.5m, Protein = 5.7m, Yag = 8.2m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 2), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tarhana.jpg" });
                besinListesi.Add(new Besin { BesinAd = "İşkembe Çorbası", Gram = 150m, Kalori = 209m, Karbonhidrat = 7.4m, Protein = 22.7m, Yag = 9.5m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 2), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 26), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "iskembe.jpg" });
                besinListesi.Add(new Besin { BesinAd = "İşkembe Çorbası", Gram = 1, Kalori = 1, Karbonhidrat = 0m, Protein = 0.2m, Yag = 0.1m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 2), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "iskembe.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Mercimek Çorbası", Gram = 300m, Kalori = 137m, Karbonhidrat = 24.8m, Protein = 7.4m, Yag = 0.6m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 2), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "mercimekCorbasi.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Mercimek Çorbası", Gram = 200m, Kalori = 91m, Karbonhidrat = 16.6m, Protein = 4.9m, Yag = 0.4m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 2), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 26), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "mercimekCorbasi.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Mercimek Çorbası", Gram = 1m, Kalori = 0.46m, Karbonhidrat = 0.1m, Protein = 0m, Yag = 0m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 2), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "mercimekCorbasi.jpg" });
                besinListesi.Add(new Besin { BesinAd = "İskender Kebap", Gram = 500m, Kalori = 755m, Karbonhidrat = 77.7m, Protein = 48.3m, Yag = 26.8m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 3), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "iskender.jpg" });
                besinListesi.Add(new Besin { BesinAd = "İskender Kebap", Gram = 700m, Kalori = 1057m, Karbonhidrat = 108.8m, Protein = 67.6m, Yag = 37.5m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 3), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 22), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "iskender.jpg" });
                besinListesi.Add(new Besin { BesinAd = "İskender Kebap", Gram = 1m, Kalori = 2m, Karbonhidrat = 0.2m, Protein = 0.1m, Yag = 0.1m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 3), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "iskender.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ali Nazik", Gram = 417m, Kalori = 407m, Karbonhidrat = 9.5m, Protein = 32.6m, Yag = 25.8m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 3), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "alinazik.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ali Nazik", Gram = 250m, Kalori = 247m, Karbonhidrat = 5.7m, Protein = 19.6m, Yag = 15.5m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 3), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 4), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "alinazik.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ali Nazik", Gram = 1m, Kalori = 0.98m, Karbonhidrat = 0m, Protein = 0.1m, Yag = 0.1m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 3), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "alinazik.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Lazanya", Gram = 272m, Kalori = 494m, Karbonhidrat = 45.4m, Protein = 21.1m, Yag = 24.6m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 3), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "lazanya.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Lazanya", Gram = 150m, Kalori = 272m, Karbonhidrat = 25m, Protein = 11.6m, Yag = 13.6m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 3), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 19), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "lazanya.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Lazanya", Gram = 1m, Kalori = 2m, Karbonhidrat = 0.2m, Protein = 0.1m, Yag = 0.1m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 3), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "lazanya.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Kısır", Gram = 110m, Kalori = 178m, Karbonhidrat = 31.7m, Protein = 4.6m, Yag = 3.8m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 4), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kısır.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Kısır", Gram = 1m, Kalori = 2m, Karbonhidrat = 0.3m, Protein = 0m, Yag = 0m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 4), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kısır.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Kısır", Gram = 15m, Kalori = 24m, Karbonhidrat = 4.3m, Protein = 0.6m, Yag = 0.5m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 4), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 23), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kısır.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Zeytinyağlı Yaprak Sarma", Gram = 33m, Kalori = 32m, Karbonhidrat = 5.9m, Protein = 1.1m, Yag = 0.4m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 4), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 2), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sarma.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Zeytinyağlı Yaprak Sarma", Gram = 130m, Kalori = 125m, Karbonhidrat = 23.2m, Protein = 4.4m, Yag = 1.7m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 4), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sarma.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Zeytinyağlı Yaprak Sarma", Gram = 20m, Kalori = 19m, Karbonhidrat = 3.6m, Protein = 0.7m, Yag = 0.3m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 4), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 3), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sarma.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Humus", Gram = 140m, Kalori = 339m, Karbonhidrat = 18.9m, Protein = 8.2m, Yag = 24.9m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 4), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "humus.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Humus", Gram = 15m, Kalori = 36m, Karbonhidrat = 2.0m, Protein = 0.9m, Yag = 2.7m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 4), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 24), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "humus.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Humus", Gram = 1m, Kalori = 2m, Karbonhidrat = 0.1m, Protein = 0.1m, Yag = 0.2m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 4), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "humus.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ekmek", Gram = 25m, Kalori = 64m, Karbonhidrat = 13.2m, Protein = 2m, Yag = 0.2m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 5), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 17), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "ekmek.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ekmek", Gram = 40m, Kalori = 102m, Karbonhidrat = 21.1m, Protein = 3.2m, Yag = 0.4m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 5), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 18), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "ekmek.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ekmek", Gram = 50m, Kalori = 128m, Karbonhidrat = 26.4m, Protein = 4m, Yag = 0.4m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 5), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 19), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "ekmek.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Peynirli Poğaça", Gram = 70m, Kalori = 274m, Karbonhidrat = 21.4m, Protein = 6.1m, Yag = 18.3m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 5), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 2), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "peynirliPogaca.jpeg" });
                besinListesi.Add(new Besin { BesinAd = "Peynirli Poğaça", Gram = 1m, Kalori = 4m, Karbonhidrat = 0.3m, Protein = 0.1m, Yag = 0.3m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 5), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "peynirliPogaca.jpeg" });
                besinListesi.Add(new Besin { BesinAd = "Cevizli Ekmek", Gram = 30m, Kalori = 149m, Karbonhidrat = 17.5m, Protein = 4.1m, Yag = 6.9m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 5), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 18), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cevizliekmek.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Cevizli Ekmek", Gram = 15m, Kalori = 74m, Karbonhidrat = 8.7m, Protein = 2m, Yag = 3.5m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 5), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 17), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cevizliekmek.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Cevizli Ekmek", Gram = 1m, Kalori = 5m, Karbonhidrat = 0.6m, Protein = 0.1m, Yag = 0.2m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 5), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cevizliekmek.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Rus Salatası", Gram = 56m, Kalori = 61m, Karbonhidrat = 5.61m, Protein = 1.30m, Yag = 3.84m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 6), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 24), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "russalatasi.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Rus Salatası", Gram = 45m, Kalori = 49m, Karbonhidrat = 4.49m, Protein = 1.04m, Yag = 3.08m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 6), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "russalatasi.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Rus Salatası", Gram = 232m, Kalori = 255m, Karbonhidrat = 23.14m, Protein = 5.36m, Yag = 15.86m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 6), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "russalatasi.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Pırasalı Salata", Gram = 140m, Kalori = 66m, Karbonhidrat = 5.67m, Protein = 2.04m, Yag = 3.48m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 6), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "pirasalisalata.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Pırasalı Salata", Gram = 20m, Kalori = 9m, Karbonhidrat = 0.61m, Protein = 0.30m, Yag = 0.84m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 6), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 23), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "pirasalisalata.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Pırasalı Salata", Gram = 100m, Kalori = 40m, Karbonhidrat = 4.05m, Protein = 1.45m, Yag = 2.84m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 6), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "pirasalisalata.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Sezar Salata", Gram = 30m, Kalori = 37m, Karbonhidrat = 2.61m, Protein = 4.30m, Yag = 1.14m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 6), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 24), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sezarsalata.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Sezar Salata", Gram = 365m, Kalori = 465m, Karbonhidrat = 24.61m, Protein = 48.30m, Yag = 18.24m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 6), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 20), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sezarsalata.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Sezar Salata", Gram = 1m, Kalori = 1m, Karbonhidrat = 0.61m, Protein = 0.30m, Yag = 0.84m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 6), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sezarsalata.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Limon Sos", Gram = 7m, Kalori = 6m, Karbonhidrat = 0.94m, Protein = 0.30m, Yag = 0.07m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 7), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 23), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "limonsos.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Limon Sos", Gram = 52m, Kalori = 46m, Karbonhidrat = 13.34m, Protein = 1.33m, Yag = 0.09m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 7), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "limonsos.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Limon Sos", Gram = 1m, Kalori = 0m, Karbonhidrat = 0.13m, Protein = 0.01m, Yag = 0.01m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 7), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "limonsos.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Çikolata Sos", Gram = 10m, Kalori = 28m, Karbonhidrat = 6.02m, Protein = 0.30m, Yag = 0.32m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 7), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 25), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cikolatasos.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Çikolata Sos", Gram = 90m, Kalori = 252m, Karbonhidrat = 54.18m, Protein = 2.30m, Yag = 2.88m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 7), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 14), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cikolatasos.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Çikolata Sos", Gram = 1m, Kalori = 2m, Karbonhidrat = 0.60m, Protein = 0.30m, Yag = 0.03m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 7), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 25), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cikolatasos.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Beyaz Sosu", Gram = 60m, Kalori = 30m, Karbonhidrat = 1.81m, Protein = 0.50m, Yag = 2.32m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 7), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "beyazsosu.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Beyaz Sosu", Gram = 15m, Kalori = 7m, Karbonhidrat = 0.42m, Protein = 0.13m, Yag = 0.58m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 7), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 23), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "beyazsosu.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Beyaz Sosu", Gram = 1m, Kalori = 0m, Karbonhidrat = 0.02m, Protein = 0.01m, Yag = 0.04m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 7), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "beyazsosu.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Baklava", Gram = 40m, Kalori = 164m, Karbonhidrat = 19.72m, Protein = 3.09m, Yag = 8.89m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 8), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 18), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "baklava.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Baklava", Gram = 40m, Kalori = 164m, Karbonhidrat = 19.72m, Protein = 3.09m, Yag = 8.89m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 8), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 4), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "baklava.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Baklava", Gram = 160m, Kalori = 658, Karbonhidrat = 79.97m, Protein = 34.30m, Yag = 34.78m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 8), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "baklava.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Sütlaç", Gram = 250m, Kalori = 263m, Karbonhidrat = 53.95m, Protein = 4.46m, Yag = 3.41m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 8), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 26), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sutlac.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Sütlaç", Gram = 20m, Kalori = 21m, Karbonhidrat = 4.95m, Protein = 0.46m, Yag = 0.41m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 8), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 25), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sutlac.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Sütlaç", Gram = 1m, Kalori = 1m, Karbonhidrat = 0.95m, Protein = 0.46m, Yag = 0.01m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 8), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sutlac.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Tiramisu", Gram = 100m, Kalori = 223m, Karbonhidrat = 32.95m, Protein = 5.46m, Yag = 6.41m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 8), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 17), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tiramisu.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Tiramisu", Gram = 175m, Kalori = 390m, Karbonhidrat = 57.95m, Protein = 9.46m, Yag = 11.41m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 8), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 19), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tiramisu.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Tiramisu", Gram = 130m, Kalori = 290m, Karbonhidrat = 42.95m, Protein = 6.86m, Yag = 8.41m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 8), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 18), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tiramisu.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ülker Çokoprens Atıştırmalık", Gram = 73m, Kalori = 112m, Karbonhidrat = 13.95m, Protein = 0.96m, Yag = 5.91m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 9), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 14), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cokoprens.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ülker Çokoprens Atıştırmalık", Gram = 4m, Kalori = 6m, Karbonhidrat = 0.75m, Protein = 0.05m, Yag = 0.41m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 9), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 2), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cokoprens.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ülker Çokoprens Atıştırmalık", Gram = 1m, Kalori = 1m, Karbonhidrat = 0.19m, Protein = 0.01m, Yag = 0.8m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 9), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "cokoprens.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ton Balıklı Kanepe", Gram = 210m, Kalori = 648m, Karbonhidrat = 27.6m, Protein = 12.46m, Yag = 54.41m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 9), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tonbaliklikanepe.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ton Balıklı Kanepe", Gram = 20m, Kalori = 61m, Karbonhidrat = 2.64m, Protein = 1.46m, Yag = 5.41m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 9), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 2), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tonbaliklikanepe.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ton Balıklı Kanepe", Gram = 1m, Kalori = 3m, Karbonhidrat = 0.13m, Protein = 0.6m, Yag = 0.41m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 9), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "tonbaliklikanepe.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Kinoa Kraker", Gram = 32m, Kalori = 104m, Karbonhidrat = 6.95m, Protein = 4.86m, Yag = 7.41m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 9), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kinoakraker.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Kinoa Kraker", Gram = 32m, Kalori = 104m, Karbonhidrat = 6.95m, Protein = 4.86m, Yag = 7.41m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 9), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 18), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kinoakraker.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Kinoa Kraker", Gram = 1m, Kalori = 3m, Karbonhidrat = 0.95m, Protein = 0.16m, Yag = 0.21m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 9), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kinoakraker.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ayran", Gram = 200m, Kalori = 100m, Karbonhidrat = 9.15m, Protein = 4.16m, Yag = 5.00m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 10), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 6), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "ayran.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ayran", Gram = 200m, Kalori = 100m, Karbonhidrat = 9.15m, Protein = 4.16m, Yag = 5.00m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 10), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 10), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "ayran.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Ayran", Gram = 350m, Kalori = 175m, Karbonhidrat = 16.95m, Protein = 7.86m, Yag = 8.71m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 10), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 9), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "ayran.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Portakal Suyu", Gram = 200m, Kalori = 120m, Karbonhidrat = 29.15m, Protein = 0.86m, Yag = 0.33m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 10), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 6), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "portakalsuyu.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Portakal Suyu", Gram = 100m, Kalori = 60m, Karbonhidrat = 14.15m, Protein = 0.46m, Yag = 0.17m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 10), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 7), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "portakalsuyu.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Portakal Suyu", Gram = 1m, Kalori = 0m, Karbonhidrat = 0.15m, Protein = 0.00m, Yag = 0.00m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 10), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 6), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "portakalsuyu.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Şalgam Suyu", Gram = 50m, Kalori = 13m, Karbonhidrat = 2.33m, Protein = 0.46m, Yag = 0.11m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 10), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "salgam.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Şalgam Suyu", Gram = 150m, Kalori = 39m, Karbonhidrat = 6.99m, Protein = 1.86m, Yag = 0.33m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 10), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 2), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "salgam.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Şalgam Suyu", Gram = 1m, Kalori = 0m, Karbonhidrat = 0.05m, Protein = 0.01m, Yag = 0.0m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 10), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "salgam.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Kaşarlı Tost", Gram = 70m, Kalori = 211m, Karbonhidrat = 23.55m, Protein = 9.46m, Yag = 9.33m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 11), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kasarlitost.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Kaşarlı Tost", Gram = 70m, Kalori = 211m, Karbonhidrat = 23.55m, Protein = 9.46m, Yag = 9.33m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 11), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 3), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kasarlitost.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Kaşarlı Tost", Gram = 1m, Kalori = 3m, Karbonhidrat = 0.35m, Protein = 0.16m, Yag = 0.13m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 11), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kasarlitost.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Sucuklu Yumurta", Gram = 131m, Kalori = 317m, Karbonhidrat = 4.45m, Protein = 17.46m, Yag = 25.33m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 11), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 20), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sucukluyumurta.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Sucuklu Yumurta", Gram = 100m, Kalori = 241m, Karbonhidrat = 3.35m, Protein = 13.46m, Yag = 19.33m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 11), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sucukluyumurta.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Sucuklu Yumurta", Gram = 50m, Kalori = 120m, Karbonhidrat = 1.65m, Protein = 6.76m, Yag = 9.73m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 11), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 11), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "sucukluyumurta.jpg" });
                besinListesi.Add(new Besin { BesinAd = "İncir Reçeli", Gram = 10m, Kalori = 9m, Karbonhidrat = 2.35m, Protein = 0.6m, Yag = 0.23m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 11), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 25), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "incirreceli.jpg" });
                besinListesi.Add(new Besin { BesinAd = "İncir Reçeli", Gram = 15m, Kalori = 14m, Karbonhidrat = 3.55m, Protein = 0.08m, Yag = 0.34m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 11), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 23), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "incirreceli.jpg" });
                besinListesi.Add(new Besin { BesinAd = "İncir Reçeli", Gram = 225m, Kalori = 220m, Karbonhidrat = 53.55m, Protein = 1.46m, Yag = 0.53m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 11), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "incirreceli.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Karnıyarık", Gram = 180m, Kalori = 99m, Karbonhidrat = 4.55m, Protein = 5.79m, Yag = 6.33m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 12), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 20), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "karniyarik.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Karnıyarık", Gram = 345m, Kalori = 191m, Karbonhidrat = 8.75m, Protein = 11.86m, Yag = 12.33m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 12), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "karniyarik.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Karnıyarık", Gram = 10m, Kalori = 5m, Karbonhidrat = 0.25m, Protein = 0.36m, Yag = 0.36m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 12), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 22), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "karniyarik.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Hamsili Pilav", Gram = 234m, Kalori = 334m, Karbonhidrat = 30.15m, Protein = 26.25m, Yag = 12.23m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 12), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "hamsilipilav.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Hamsili Pilav", Gram = 300m, Kalori = 436m, Karbonhidrat = 39.52m, Protein = 34.55m, Yag = 16.03m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 12), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 22), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "hamsilipilav.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Hamsili Pilav", Gram = 15m, Kalori = 21m, Karbonhidrat = 1.98m, Protein = 1.76m, Yag = 0.83m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 12), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 24), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "hamsilipilav.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Mantı", Gram = 300m, Kalori = 508m, Karbonhidrat = 89.15m, Protein = 12.36m, Yag = 10.33m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 12), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 27), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "manti.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Mantı", Gram = 10m, Kalori = 16m, Karbonhidrat = 2.95m, Protein = 0.46m, Yag = 0.35m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 12), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 23), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "manti.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Mantı", Gram = 190m, Kalori = 322m, Karbonhidrat = 56.15m, Protein = 7.86m, Yag = 6.53m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 12), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "manti.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Portakal", Gram = 100m, Kalori = 46m, Karbonhidrat = 11.55m, Protein = 0.86m, Yag = 0.33m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 13), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 25), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "portakal.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Portakal", Gram = 220m, Kalori = 101m, Karbonhidrat = 25.55m, Protein = 1.76m, Yag = 0.46m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 13), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 25), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "portakal.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Portakal", Gram = 300m, Kalori = 138m, Karbonhidrat = 34.55m, Protein = 2.46m, Yag = 0.63m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 13), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 25), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "portakal.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Kuru Yemiş", Gram = 40m, Kalori = 204m, Karbonhidrat = 14.05m, Protein = 6.36m, Yag = 13.0m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 13), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 24), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kuruyemis.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Kuru Yemiş", Gram = 100m, Kalori = 512m, Karbonhidrat = 35.55m, Protein = 15.86m, Yag = 32.50m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 13), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 26), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kuruyemis.jpgı" });
                besinListesi.Add(new Besin { BesinAd = "Kuru Yemiş", Gram = 1m, Kalori = 5m, Karbonhidrat = 0.55m, Protein = 0.33m, Yag = 0.43m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 13), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 1), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "kuruyemis.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Yeşil Kahve", Gram = 25m, Kalori = 10m, Karbonhidrat = 2.55m, Protein = 1.33m, Yag = 1.43m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 13), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 21), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "yesilkahve.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Yeşil Kahve", Gram = 1m, Kalori = 5m, Karbonhidrat = 1.5m, Protein = 0.33m, Yag = 0.53m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 13), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 18), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "yesilkahve.jpg" });
                besinListesi.Add(new Besin { BesinAd = "Yeşil Kahve", Gram = 1m, Kalori = 4m, Karbonhidrat = 0.5m, Protein = 0.20m, Yag = 0.23m, Kategori = kategoriListesi.FirstOrDefault(x => x.Id == 13), Porsiyon = porsiyonListesi.FirstOrDefault(x => x.Id == 18), BesinResimYolu = Environment.CurrentDirectory.Replace("bin\\Debug", "") + "Images\\Besin\\" + "yesilkahve.jpg" });
                foreach (Besin item in besinListesi)
                {
                    context.Besinler.Add(item);
                }
            }
            context.SaveChanges();
        }
    }
}
